version: '3'

services:
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
  caddy:
    container_name: caddy
    image: caddy
    ports:
      - 80:80
    volumes:
      - ./caddy:/usr/bin/caddy
      - ./Caddyfile:/etc/caddy/Caddyfile
    environment:
      - IPBASE_API_TOKEN
    depends_on:
      - redis