name: deploy

on:
  push:
    branches:
      - main

env:
  PLATFORMS: linux/arm/v7,linux/amd64,linux/arm64

jobs:
  semver:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tagging.outputs.new_tag }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - id: vars
      run: |
        echo ::set-output name=go_version::$(curl -s https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep -oE '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | head -1 | cut -d':' -f2 | sed 's/ //g; s/"//g')
        echo "Using Go version ${{ steps.vars.outputs.go_version }}"
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ steps.vars.outputs.go_version }}
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.26.0
      id: tagging
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        RELEASE_BRANCHES: main
        DEFAULT_BUMP: minor
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: GoReportCard
      uses: creekorful/goreportcard-action@v1.0
  docker:
    runs-on: ubuntu-latest
    needs: semver
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push latest
        id: docker_build_latest
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ github.repository }}:latest
          platforms: ${{ env.PLATFORMS }}
      - name: Build and push versioned
        id: docker_build_versioned
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ github.repository }}:${{ needs.semver.outputs.tag }}
          platforms: ${{ env.PLATFORMS }}
