name: deploy

on:
  push:
    branches:
      - main

env:
  PLATFORMS: linux/arm/v7,linux/amd64,linux/arm64

jobs:
  semver:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tagging.outputs.new_tag }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    - name: Install Go
      uses: actions/setup-go@v5
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.61.0
      id: tagging
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        RELEASE_BRANCHES: main
        DEFAULT_BUMP: minor
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: GoReportCard
      uses: creekorful/goreportcard-action@v1.0
  docker:
    runs-on: ubuntu-latest
    needs: semver
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push latest
        id: docker_build_latest
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ github.repository }}:latest
          platforms: ${{ env.PLATFORMS }}
      - name: Build and push versioned
        id: docker_build_versioned
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ github.repository }}:${{ needs.semver.outputs.tag }}
          platforms: ${{ env.PLATFORMS }}
